export interface Report {
  id: number
  name: string
  description: string
}

export interface ReportCategory {
  id: number
  name: string
  description: string
  color: string
  reports: Report[]
}

export const reportCategories: ReportCategory[] = [
  {
    id: 1,
    name: 'Financial',
    description: 'Settlement statements, revenue reports, and financial documentation.',
    color: '#1B5E20',
    reports: [
      {
        id: 101,
        name: 'Driver Sign On Documents',
        description: 'View and download sign-on documentation for all active drivers under your agent code, including W-9 forms and direct deposit authorizations.',
      },
      {
        id: 102,
        name: 'Settlement Detail Report',
        description: 'Detailed breakdown of weekly settlement calculations including linehaul, fuel surcharge, deductions, and net pay by driver.',
      },
      {
        id: 103,
        name: 'Revenue Summary by Lane',
        description: 'Summary of revenue generated by lane for the selected date range, sortable by origin, destination, and total revenue.',
      },
    ],
  },
  {
    id: 2,
    name: 'Safety',
    description: 'Inspection results, roadside reports, and safety compliance data.',
    color: '#B71C1C',
    reports: [
      {
        id: 201,
        name: 'Roadside Inspection Reports',
        description: 'Complete history of roadside inspections including Level I through Level V results, violations found, and out-of-service events.',
      },
      {
        id: 202,
        name: 'Inspection Stations',
        description: 'Directory of active inspection stations along common Kaplan routes with hours of operation and known enforcement patterns.',
      },
      {
        id: 203,
        name: 'Clinic Locations',
        description: 'Approved DOT physical examination clinics and drug testing facilities near Kaplan terminals and common routes.',
      },
    ],
  },
  {
    id: 3,
    name: 'Operations',
    description: 'Driver status, equipment tracking, and operational performance metrics.',
    color: '#0D47A1',
    reports: [
      {
        id: 301,
        name: 'Pending Drivers',
        description: 'List of drivers currently in the onboarding pipeline with application status, background check progress, and estimated clearance dates.',
      },
      {
        id: 302,
        name: 'Driver Log Codes',
        description: 'Reference guide for ELD duty status codes, exception codes, and special driving condition annotations used in Kaplan systems.',
      },
      {
        id: 303,
        name: 'Equipment Utilization Report',
        description: 'Utilization metrics for trailers and tractors assigned to your agent code including idle time, loaded miles percentage, and maintenance status.',
      },
    ],
  },
  {
    id: 4,
    name: 'Compliance',
    description: 'Regulatory compliance status, audit results, and remedial actions.',
    color: '#E65100',
    reports: [
      {
        id: 401,
        name: 'Compliance Report',
        description: 'Overall compliance scorecard showing CSA BASIC scores, ISS percentiles, and areas requiring corrective action for your fleet.',
      },
      {
        id: 402,
        name: 'Remedial Review',
        description: 'Drivers flagged for remedial safety review based on inspection history, HOS violations, or accident involvement. Includes required action items.',
      },
    ],
  },
]
